version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_SECRET_KEY=your-secret-key
      - ENCRYPTION_KEY=your-generated-fernet-key-here
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/strategies:/app/strategies
      - ./.env:/app/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:5000/api