#!/usr/bin/env python3
"""
AI Trading Sentinel - Secrets Management Setup
TRAE-SentinelOps Production Deployment Secrets Generator

This script generates secure environment variables and sets up secrets management.
"""

import os
import secrets
import string
import json
from pathlib import Path
from typing import Dict, List
import base64

def generate_secure_key(length: int = 32) -> str:
    """Generate a cryptographically secure random key"""
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*"
    return ''.join(secrets.choice(alphabet) for _ in range(length))

def generate_jwt_secret() -> str:
    """Generate a secure JWT secret key"""
    return base64.b64encode(secrets.token_bytes(32)).decode('utf-8')

def generate_flask_secret() -> str:
    """Generate a secure Flask secret key"""
    return secrets.token_hex(24)

def create_sample_env_file():
    """Create a sample .env file with secure defaults and placeholders"""
    
    # Generate secure keys
    flask_secret = generate_flask_secret()
    jwt_secret = generate_jwt_secret()
    
    env_content = f"""# AI Trading Sentinel - Production Environment Variables
# Generated by TRAE-SentinelOps Secrets Manager
# 
# SECURITY WARNING: Keep this file secure and never commit to version control!
# This file contains sensitive credentials and API keys.

# =============================================================================
# VPS DEPLOYMENT CONFIGURATION
# =============================================================================
# Your Contabo VPS IP address (e.g., 192.168.1.100)
CONTABO_VPS_IP=YOUR_VPS_IP_HERE

# VPS username (usually 'root' or your custom user)
CONTABO_VPS_USER=root

# Path to your SSH private key file (e.g., C:\\Users\\YourName\\.ssh\\id_rsa)
CONTABO_SSH_KEY_PATH=C:\\Users\\Admin\\.ssh\\contabo_key

# =============================================================================
# GITHUB INTEGRATION
# =============================================================================
# GitHub Personal Access Token (starts with ghp_)
# Generate at: https://github.com/settings/tokens
# Required scopes: repo, workflow
GITHUB_TOKEN=ghp_YOUR_GITHUB_TOKEN_HERE

# Your GitHub repository URL
GITHUB_REPO_URL=https://github.com/YOUR_USERNAME/ai-trading-sentinel.git

# =============================================================================
# TRADING PLATFORM CREDENTIALS
# =============================================================================
# Bulenox trading platform credentials
BULENOX_USERNAME=your_bulenox_username
BULENOX_PASSWORD=your_bulenox_password

# =============================================================================
# WEB APPLICATION SECURITY
# =============================================================================
# Flask application secret key (auto-generated)
FLASK_SECRET_KEY={flask_secret}

# JWT token secret key (auto-generated)
JWT_SECRET_KEY={jwt_secret}

# =============================================================================
# MONITORING AND ALERTS
# =============================================================================
# Slack webhook URL for alerts
# Create at: https://api.slack.com/messaging/webhooks
SLACK_WEBHOOK_URL=https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK

# =============================================================================
# OPTIONAL: ENHANCED MONITORING
# =============================================================================
# Email notifications (SMTP)
# SMTP_SERVER=smtp.gmail.com
# SMTP_USERNAME=your_email@gmail.com
# SMTP_PASSWORD=your_app_password

# Telegram notifications
# TELEGRAM_BOT_TOKEN=your_telegram_bot_token
# TELEGRAM_CHAT_ID=your_telegram_chat_id

# =============================================================================
# OPTIONAL: SECURITY CONFIGURATION
# =============================================================================
# API rate limiting (requests per minute)
API_RATE_LIMIT=100

# CORS allowed origins (comma-separated)
API_CORS_ORIGINS=http://localhost:3000,https://your-domain.com

# SSL certificate paths (for HTTPS)
# SSL_CERT_PATH=/path/to/certificate.crt
# SSL_KEY_PATH=/path/to/private.key

# =============================================================================
# OPTIONAL: TRADING CONFIGURATION
# =============================================================================
# Risk management settings (percentages)
TRADING_MAX_RISK_PERCENT=2.0
TRADING_STOP_LOSS_PERCENT=1.0
TRADING_TAKE_PROFIT_PERCENT=2.0

# =============================================================================
# PRODUCTION DEPLOYMENT FLAGS
# =============================================================================
# Environment mode
FLASK_ENV=production
DEBUG=False

# Database configuration
DATABASE_URL=sqlite:///trading_sentinel.db

# Log level
LOG_LEVEL=INFO
"""
    
    # Write to .env file
    with open('.env', 'w', encoding='utf-8') as f:
        f.write(env_content)
    
    return {
        'flask_secret': flask_secret,
        'jwt_secret': jwt_secret,
        'file_created': True
    }

def create_deployment_secrets_guide():
    """Create a comprehensive secrets setup guide"""
    
    guide_content = """# 🔐 AI Trading Sentinel - Secrets Management Guide

## Overview
This guide helps you securely configure all required environment variables for production deployment.

## 🚨 Security Best Practices

1. **Never commit `.env` files to version control**
2. **Use strong, unique passwords for all accounts**
3. **Enable 2FA on all external services**
4. **Regularly rotate API keys and tokens**
5. **Use SSH key authentication for VPS access**

## 📋 Required Setup Steps

### 1. VPS Configuration

```bash
# Generate SSH key pair (run on your local machine)
ssh-keygen -t rsa -b 4096 -f ~/.ssh/contabo_key

# Copy public key to VPS
ssh-copy-id -i ~/.ssh/contabo_key.pub root@YOUR_VPS_IP
```

**Environment Variables:**
- `CONTABO_VPS_IP`: Your Contabo VPS IP address
- `CONTABO_VPS_USER`: Usually 'root' or your custom user
- `CONTABO_SSH_KEY_PATH`: Path to your SSH private key

### 2. GitHub Integration

1. Go to [GitHub Settings > Developer settings > Personal access tokens](https://github.com/settings/tokens)
2. Click "Generate new token (classic)"
3. Select scopes: `repo`, `workflow`
4. Copy the generated token (starts with `ghp_`)

**Environment Variables:**
- `GITHUB_TOKEN`: Your GitHub personal access token
- `GITHUB_REPO_URL`: Your repository URL

### 3. Trading Platform

1. Create account on [Bulenox](https://bulenox.projectx.com/login)
2. Verify your account and complete KYC if required
3. Note your login credentials

**Environment Variables:**
- `BULENOX_USERNAME`: Your Bulenox username
- `BULENOX_PASSWORD`: Your Bulenox password

### 4. Monitoring Setup

#### Slack Notifications
1. Go to [Slack API](https://api.slack.com/messaging/webhooks)
2. Create a new webhook for your workspace
3. Copy the webhook URL

**Environment Variables:**
- `SLACK_WEBHOOK_URL`: Your Slack webhook URL

#### Optional: Email Notifications
For Gmail SMTP:
1. Enable 2-factor authentication
2. Generate an app password
3. Use `smtp.gmail.com` as server

#### Optional: Telegram Notifications
1. Create a bot via [@BotFather](https://t.me/botfather)
2. Get your chat ID from [@userinfobot](https://t.me/userinfobot)

## 🔧 Configuration Commands

```bash
# Generate secure .env file with defaults
python setup_secrets.py --generate

# Validate environment configuration
python validate_environment.py

# Test VPS connection
python setup_secrets.py --test-vps

# Test GitHub integration
python setup_secrets.py --test-github
```

## 🚀 Deployment Readiness Checklist

- [ ] VPS accessible via SSH key
- [ ] GitHub token has required permissions
- [ ] Bulenox credentials verified
- [ ] Slack webhook configured
- [ ] All required environment variables set
- [ ] Environment validation passes

## 🔍 Troubleshooting

### SSH Connection Issues
```bash
# Test SSH connection
ssh -i ~/.ssh/contabo_key root@YOUR_VPS_IP

# Fix permissions
chmod 600 ~/.ssh/contabo_key
```

### GitHub Token Issues
- Ensure token has `repo` and `workflow` scopes
- Check token expiration date
- Verify repository access

### Trading Platform Issues
- Verify account is active and verified
- Check for any account restrictions
- Ensure correct login URL: https://bulenox.projectx.com/login

## 📞 Support

If you encounter issues:
1. Run `python validate_environment.py` for diagnostics
2. Check the generated `environment_validation_report.json`
3. Review logs in the `logs/` directory

---
**TRAE-SentinelOps** - Automated Production Deployment System
"""
    
    with open('SECRETS_SETUP_GUIDE.md', 'w', encoding='utf-8') as f:
        f.write(guide_content)
    
    return True

def test_vps_connection(vps_ip: str, vps_user: str, ssh_key_path: str) -> Dict:
    """Test VPS SSH connection"""
    import subprocess
    
    try:
        # Test SSH connection
        cmd = f'ssh -i "{ssh_key_path}" -o ConnectTimeout=10 -o StrictHostKeyChecking=no {vps_user}@{vps_ip} "echo Connection successful"'
        result = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=15)
        
        return {
            'success': result.returncode == 0,
            'output': result.stdout.strip(),
            'error': result.stderr.strip() if result.stderr else None
        }
    except Exception as e:
        return {
            'success': False,
            'output': None,
            'error': str(e)
        }

def test_github_connection(github_token: str, repo_url: str) -> Dict:
    """Test GitHub API connection"""
    try:
        import requests
        
        # Extract owner/repo from URL
        if 'github.com/' in repo_url:
            parts = repo_url.split('github.com/')[-1].replace('.git', '').split('/')
            if len(parts) >= 2:
                owner, repo = parts[0], parts[1]
                
                # Test GitHub API
                headers = {'Authorization': f'token {github_token}'}
                response = requests.get(f'https://api.github.com/repos/{owner}/{repo}', headers=headers)
                
                return {
                    'success': response.status_code == 200,
                    'output': f'Repository access confirmed: {owner}/{repo}',
                    'error': response.text if response.status_code != 200 else None
                }
        
        return {
            'success': False,
            'output': None,
            'error': 'Invalid repository URL format'
        }
    except Exception as e:
        return {
            'success': False,
            'output': None,
            'error': str(e)
        }

def main():
    """Main setup function"""
    import sys
    
    if len(sys.argv) > 1:
        if sys.argv[1] == '--generate':
            print("🔐 Generating secure environment configuration...")
            
            # Create .env file with secure defaults
            result = create_sample_env_file()
            
            if result['file_created']:
                print("✅ Created .env file with secure defaults")
                print(f"   • Flask Secret: {result['flask_secret'][:10]}...")
                print(f"   • JWT Secret: {result['jwt_secret'][:10]}...")
                print("\n📝 Next steps:")
                print("   1. Edit .env file with your actual credentials")
                print("   2. Run: python validate_environment.py")
                print("   3. Follow SECRETS_SETUP_GUIDE.md for detailed setup")
            
            # Create setup guide
            create_deployment_secrets_guide()
            print("✅ Created SECRETS_SETUP_GUIDE.md")
            
            return
        
        elif sys.argv[1] == '--test-vps':
            vps_ip = os.getenv('CONTABO_VPS_IP')
            vps_user = os.getenv('CONTABO_VPS_USER')
            ssh_key = os.getenv('CONTABO_SSH_KEY_PATH')
            
            if not all([vps_ip, vps_user, ssh_key]):
                print("❌ Missing VPS environment variables")
                print("   Set: CONTABO_VPS_IP, CONTABO_VPS_USER, CONTABO_SSH_KEY_PATH")
                return
            
            print(f"🔍 Testing VPS connection to {vps_ip}...")
            result = test_vps_connection(vps_ip, vps_user, ssh_key)
            
            if result['success']:
                print(f"✅ VPS connection successful: {result['output']}")
            else:
                print(f"❌ VPS connection failed: {result['error']}")
            
            return
        
        elif sys.argv[1] == '--test-github':
            github_token = os.getenv('GITHUB_TOKEN')
            repo_url = os.getenv('GITHUB_REPO_URL')
            
            if not all([github_token, repo_url]):
                print("❌ Missing GitHub environment variables")
                print("   Set: GITHUB_TOKEN, GITHUB_REPO_URL")
                return
            
            print(f"🔍 Testing GitHub connection...")
            result = test_github_connection(github_token, repo_url)
            
            if result['success']:
                print(f"✅ GitHub connection successful: {result['output']}")
            else:
                print(f"❌ GitHub connection failed: {result['error']}")
            
            return
    
    # Default: Show help
    print("🔐 AI Trading Sentinel - Secrets Management Setup")
    print("=" * 50)
    print("\nUsage:")
    print("  python setup_secrets.py --generate      Generate secure .env file")
    print("  python setup_secrets.py --test-vps      Test VPS SSH connection")
    print("  python setup_secrets.py --test-github   Test GitHub API connection")
    print("\nFor detailed setup instructions, see SECRETS_SETUP_GUIDE.md")

if __name__ == '__main__':
    main()