apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 15s
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: loki
    secureJsonData: {}

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: prometheus
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
    secureJsonData: {}

  - name: AlertManager
    type: alertmanager
    access: proxy
    orgId: 1
    url: http://alertmanager:9093
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      implementation: prometheus
    secureJsonData: {}

  - name: PostgreSQL
    type: postgres
    access: proxy
    orgId: 1
    url: postgres:5432
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1300
      timescaledb: false
    secureJsonData:
      password: ${POSTGRES_PASSWORD}

  - name: Redis
    type: redis-datasource
    access: proxy
    orgId: 1
    url: redis://redis:6379
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      client: standalone
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    secureJsonData:
      password: ${REDIS_PASSWORD}