name: Setup GitHub Secrets Guide

on:
  workflow_dispatch:

jobs:
  display_guide:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Display GitHub Secrets Setup Guide
        run: |
          echo "=== GitHub Secrets Setup Guide for AI Trading Sentinel ==="
          echo ""
          echo "To securely deploy your trading bot, you need to set up the following secrets in your GitHub repository:"
          echo ""
          echo "1. Go to your GitHub repository"
          echo "2. Click on 'Settings' tab"
          echo "3. In the left sidebar, click on 'Secrets and variables' > 'Actions'"
          echo "4. Click on 'New repository secret' to add each of the following:"
          echo ""
          echo "Required secrets for deployment:"
          echo "- CONTABO_VPS_IP: Your Contabo VPS IP address"
          echo "- CONTABO_VPS_PASSWORD: Your Contabo VPS password"
          echo "- CONTABO_SSH_PORT: Your Contabo SSH port (usually 22)"
          echo ""
          echo "Optional secrets for notifications:"
          echo "- SLACK_BOT_TOKEN: Your Slack bot token for notifications"
          echo "- SLACK_CHANNEL_ID: Your Slack channel ID for notifications"
          echo ""
          echo "These secrets will be securely used in the CI/CD pipeline without being exposed in logs."
          echo ""
          echo "For more information on GitHub Secrets, visit: https://docs.github.com/en/actions/security-guides/encrypted-secrets"